name: hetu_xx
description: Hetu is a lightweight scripting language for embedding in Flutter apps.
version: 0.6.2
homepage: https://github.com/hetu-script/hetu-script
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  quiver: ^3.0.1
  pub_semver: ^2.1.0
  path: ^1.8.0
  recase: ^4.0.0
  meta: ^1.7.0
  characters: ^1.2.0
  fast_noise: ^2.0.0
