import "dart:io";

import "package:hetu_xx/precompiled_module.dart";
import "package:hooks/hooks.dart";
import "package:code_assets/code_assets.dart";

const assetName = 'lib/asset.dart';

void main(List<String> args) async {
  await build(args, (input, output) async {
    final packageName = input.packageName;
    final assetPath = input.packageRoot.resolve(assetName);
    // === 1. Куда писать файлы ===

    // === 3. Реальный файл на диске ===
    final file = File(assetPath.toFilePath());

    const useSomeAsset = bool.fromEnvironment("hookbuild", defaultValue: false);

    if (useSomeAsset) {
      await file.writeAsString("""
// generated by hook
import 'dart:typed_data';

const myStdLibBytes = <int>[1, 2, 3, 4];

final stdLib = Uint8List.fromList(myStdLibBytes);


    """);
      output.assets.code.add(
        CodeAsset(
          package: packageName,
          name: 'asset.dart',
          file: assetPath,
          linkMode: LookupInProcess(),
        ),
      );
    } else {
      await file.writeAsString("""
// generated by hook
import 'dart:typed_data';

const myStdLibBytes = <int>${hetuCoreModule.toString()};

final stdLib = Uint8List.fromList(myStdLibBytes);


    """);
    }

    output.assets.code.add(
      CodeAsset(
        package: packageName,
        name: 'asset.dart',
        file: assetPath,
        linkMode: LookupInProcess(),
      ),
    );
  });
}
