name: hetu_script
description: Hetu is a lightweight scripting language for embedding in Flutter apps.
version: 0.6.2
homepage: https://github.com/hetu-script/hetu-script

environment:
  sdk: ^3.6.0

dependencies:
  quiver: ^3.0.1
  pub_semver: ^2.1.0
  path: ^1.8.0
  recase: ^4.0.0
  meta: ^1.7.0
  characters: ^1.2.0
  fast_noise: ^2.0.0

dev_dependencies:
  lints: ^5.1.0
  test: ^1.26.0
  analyzer: ^7.7.0
