name: hetu_script
description: Hetu is a lightweight script language for embedding in Flutter apps.
version: 0.3.8
homepage: https://github.com/hetu-script/hetu-script
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.1
  pub_semver: ^2.1.0
  path: ^1.8.0
  recase: ^4.0.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.7
  analyzer: ^2.7.0
