name: hetu_language_server
description: Hetu Script language server
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  args: ^2.0.0
  path: ^1.8.0
  hetu_script:
    path: ../package/
  hetu_script_dev_tools:
    path: ../dev_tools/

dev_dependencies:
  pedantic: ^1.11.0
  meta: ^1.3.0
