name: hetu_script_code_pad
description: Hetu Script Code Pad.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  code_text_field: ^1.0.2
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0

  hetu_xx:
    path: ../hetu_xx
  hetu_script_flutter:
    path: ../hetu_script_flutter

dev_dependencies:
  lints: ^5.1.0
  test: ^1.26.0
  analyzer: ^7.7.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/canvaskit/profiling/

  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMonoCJKsc-Regular.otf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMonoDerivativePowerline.ttf
