name: hetu_script_tools
description: Hetu Script tools
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hetu_script:
    path: ../packages/hetu_script
  hetu_script_dev_tools:
    path: ../packages/hetu_script_dev_tools

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.19.4
