name: hetu_script_nlp_plugin
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  hetu_script:
    path: ../hetu_script
  hetu_script_dev_tools:
    path: ../hetu_script_dev_tools

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
